version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
      - npm install
  build:
    commands:
      - echo "No build necessary for a personal website"
  post_build:
    commands:
      - echo "Post build phase"
 
